Logging:
  LogLevel:
    Default: Debug
    Microsoft.AspNetCore: Warning

AllowedHosts: "*"
  
BotConfiguration:
    BotToken: 123:xxxxx
    SubstitutionsCheckPeriod: 1h
    ChatInfoDirectory: ./chat-info
    
SubstitutionCache:
  CacheDuration: 1h
  