Logging:
  LogLevel:
    Default: Debug
    Microsoft.AspNetCore: Warning

AllowedHosts: "*"
  
BotConfiguration:
    BotToken: 123:xxxxx
    SubstitutionsCheckPeriod: 1h
    ChatInfoDirectory: ./chat-info
    
SubstitutionCache:
  CacheDuration: 1h
  
Serilog:
  Using:
    - Serilog.Sinks.File
    - Serilog.Sinks.Console
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft.AspNetCore: Warning
  WriteTo:
    - Name: File
      Args:
        path: logs/.log
        rollingInterval: Day
        retainedFileCountLimit: 30
        outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
    - Name: Console
      Args:
        outputTemplate: "{Timestamp:HH:mm:ss} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
