version: '3.7'

services:
  tkvgbot:
    build:
      context: .
      dockerfile: ./TkvgSubstitutionBot/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001      
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"